USE [master]
GO

/****** Object:  Database [PeopleDB]    Script Date: 2/23/2020 11:25:35 AM ******/
CREATE DATABASE [PeopleDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PeopleDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PeopleDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PeopleDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PeopleDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PeopleDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PeopleDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PeopleDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PeopleDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PeopleDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PeopleDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PeopleDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PeopleDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PeopleDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PeopleDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PeopleDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PeopleDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PeopleDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PeopleDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PeopleDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PeopleDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PeopleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PeopleDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PeopleDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PeopleDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PeopleDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PeopleDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PeopleDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PeopleDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PeopleDB] SET  MULTI_USER 
GO

ALTER DATABASE [PeopleDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PeopleDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PeopleDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PeopleDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PeopleDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PeopleDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PeopleDB] SET  READ_WRITE 
GO

